/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntregaRouteImport } from './routes/entrega'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as AnuncioSlugRouteImport } from './routes/anuncio.$slug'
import { Route as ApiPublicBspayWebhookRouteImport } from './routes/api/public/bspay-webhook'
import { Route as AdminAnuncioIdRouteImport } from './routes/admin.anuncio.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaRoute = EntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncioSlugRoute = AnuncioSlugRouteImport.update({
  id: '/anuncio/$slug',
  path: '/anuncio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBspayWebhookRoute = ApiPublicBspayWebhookRouteImport.update({
  id: '/api/public/bspay-webhook',
  path: '/api/public/bspay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnuncioIdRoute = AdminAnuncioIdRouteImport.update({
  id: '/anuncio/$id',
  path: '/anuncio/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacoes': typeof AvaliacoesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/conversas': typeof ConversasRoute
  '/entrega': typeof EntregaRoute
  '/login': typeof LoginRoute
  '/anuncio/$slug': typeof AnuncioSlugRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/anuncio/$id': typeof AdminAnuncioIdRoute
  '/api/public/bspay-webhook': typeof ApiPublicBspayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacoes': typeof AvaliacoesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/conversas': typeof ConversasRoute
  '/entrega': typeof EntregaRoute
  '/login': typeof LoginRoute
  '/anuncio/$slug': typeof AnuncioSlugRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/anuncio/$id': typeof AdminAnuncioIdRoute
  '/api/public/bspay-webhook': typeof ApiPublicBspayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacoes': typeof AvaliacoesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/conversas': typeof ConversasRoute
  '/entrega': typeof EntregaRoute
  '/login': typeof LoginRoute
  '/anuncio/$slug': typeof AnuncioSlugRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/anuncio/$id': typeof AdminAnuncioIdRoute
  '/api/public/bspay-webhook': typeof ApiPublicBspayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliacoes'
    | '/chat'
    | '/checkout'
    | '/conversas'
    | '/entrega'
    | '/login'
    | '/anuncio/$slug'
    | '/item/$id'
    | '/admin/anuncio/$id'
    | '/api/public/bspay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avaliacoes'
    | '/chat'
    | '/checkout'
    | '/conversas'
    | '/entrega'
    | '/login'
    | '/anuncio/$slug'
    | '/item/$id'
    | '/admin/anuncio/$id'
    | '/api/public/bspay-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliacoes'
    | '/chat'
    | '/checkout'
    | '/conversas'
    | '/entrega'
    | '/login'
    | '/anuncio/$slug'
    | '/item/$id'
    | '/admin/anuncio/$id'
    | '/api/public/bspay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvaliacoesRoute: typeof AvaliacoesRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  ConversasRoute: typeof ConversasRoute
  EntregaRoute: typeof EntregaRoute
  LoginRoute: typeof LoginRoute
  AnuncioSlugRoute: typeof AnuncioSlugRoute
  ItemIdRoute: typeof ItemIdRoute
  ApiPublicBspayWebhookRoute: typeof ApiPublicBspayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega': {
      id: '/entrega'
      path: '/entrega'
      fullPath: '/entrega'
      preLoaderRoute: typeof EntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncio/$slug': {
      id: '/anuncio/$slug'
      path: '/anuncio/$slug'
      fullPath: '/anuncio/$slug'
      preLoaderRoute: typeof AnuncioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bspay-webhook': {
      id: '/api/public/bspay-webhook'
      path: '/api/public/bspay-webhook'
      fullPath: '/api/public/bspay-webhook'
      preLoaderRoute: typeof ApiPublicBspayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/anuncio/$id': {
      id: '/admin/anuncio/$id'
      path: '/anuncio/$id'
      fullPath: '/admin/anuncio/$id'
      preLoaderRoute: typeof AdminAnuncioIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnuncioIdRoute: typeof AdminAnuncioIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnuncioIdRoute: AdminAnuncioIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvaliacoesRoute: AvaliacoesRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  ConversasRoute: ConversasRoute,
  EntregaRoute: EntregaRoute,
  LoginRoute: LoginRoute,
  AnuncioSlugRoute: AnuncioSlugRoute,
  ItemIdRoute: ItemIdRoute,
  ApiPublicBspayWebhookRoute: ApiPublicBspayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
